import type { TextFragment } from '@casys/core';
import type { AITextModelPort } from '@casys/application';

import { createLogger, type Logger } from '../../../../../../utils/logger';
import type { ArticleGenerationState } from '../article-generation.state';
import { applyTextFragments } from '../utils/text-fragment.utils';

export interface RefineSectionsNodeDeps {
  logger?: Logger;
  aiModel: AITextModelPort;
}

/**
 * Refine Sections Node - Apply TextFragments with Fuzzy Context Matching
 *
 * Applies TextFragment patches generated by reviewArticleNode:
 * - Uses fuzzy context matching for robust text location
 * - Tracks which sections were modified (recentlyModifiedIds) for smart validation
 * - 37% token reduction per patch vs full rewrites
 */
export async function refineSectionsNode(
  state: ArticleGenerationState,
  deps: RefineSectionsNodeDeps
): Promise<ArticleGenerationState> {
  const logger = deps.logger ?? createLogger('ArticleGeneration.refineSections');

  // Check if we have TextFragments to apply
  const hasTextFragments =
    state.textFragments && Array.isArray(state.textFragments) && state.textFragments.length > 0;

  if (!hasTextFragments) {
    logger.log?.('[refineSections] No text fragments to apply, skipping');
    return { ...state, attempts: state.attempts + 1 };
  }

  // Apply TextFragments with fuzzy matching
  return await applyTextFragmentsMode(state, deps, logger);
}

/**
 * NEW MODE: Apply TextFragments with fuzzy context matching
 */
async function applyTextFragmentsMode(
  state: ArticleGenerationState,
  deps: RefineSectionsNodeDeps,
  logger: Logger
): Promise<ArticleGenerationState> {
  logger.log?.(
    `[refineSections] Applying ${state.textFragments!.length} text fragments with fuzzy matching`
  );

  // DEBUG: Log all fragments before applying
  for (let i = 0; i < state.textFragments!.length; i++) {
    const frag = state.textFragments![i];
    const metadata = (frag as any).metadata;
    logger.log?.(`[refineSections] Fragment ${i + 1}/${state.textFragments!.length}`, {
      fragmentId: frag.id,
      sectionId: frag.sectionId,
      position: frag.position,
      contentLength: frag.content.length,
      contentPreview: frag.content.substring(0, 100),
      hasTarget: !!metadata?.target,
      targetPreview: metadata?.target?.substring(0, 80),
      contextBeforeLines: metadata?.contextBefore?.length ?? 0,
      contextAfterLines: metadata?.contextAfter?.length ?? 0,
    });
  }

  const updated = [...state.sections];
  const modifiedSectionIds = new Set<string>();

  // Group fragments by section for efficient batch application
  const fragmentsBySectionId = new Map<string, TextFragment[]>();

  for (const fragment of state.textFragments!) {
    if (!fragmentsBySectionId.has(fragment.sectionId)) {
      fragmentsBySectionId.set(fragment.sectionId, []);
    }
    fragmentsBySectionId.get(fragment.sectionId)!.push(fragment);
  }

  // Apply fragments to each section
  for (const [sectionId, fragments] of fragmentsBySectionId) {
    const section = updated.find(s => s.id === sectionId);
    if (!section) {
      logger.warn?.(`[refineSections] Section ${sectionId} not found, skipping fragments`);
      continue;
    }

    logger.log?.(
      `[refineSections] Applying ${fragments.length} fragments to section "${section.title}"`
    );

    // Apply all fragments to this section
    const result = applyTextFragments(section.content, fragments, {
      verbose: true, // ENABLED: Detailed fuzzy matching debug logs
      targetThreshold: 0.85,
      contextThreshold: 0.7,
      combinedThreshold: 0.8,
    });

    if (result.applied > 0) {
      // Update section content
      section.content = result.content;
      modifiedSectionIds.add(sectionId);

      logger.log?.(
        `[refineSections] Section "${section.title}": ${result.applied}/${fragments.length} fragments applied successfully`
      );

      if (result.failed > 0) {
        logger.warn?.(
          `[refineSections] Section "${section.title}": ${result.failed} fragments failed to apply`
        );
        // DEBUG: Log detailed failure info for each failed fragment
        for (const res of result.results) {
          if (!res.applied) {
            const fragment = fragments.find(f => f.id === (res.match as any)?.fragmentId);
            logger.error?.(
              `[refineSections] Fragment failure details`,
              {
                fragmentId: fragment?.id,
                reason: res.reason,
                targetScore: res.match?.targetScore,
                contextBeforeScore: res.match?.contextBeforeScore,
                contextAfterScore: res.match?.contextAfterScore,
                combinedScore: res.match?.combinedScore,
                expectedTarget: fragment?.metadata?.target?.substring(0, 80),
              }
            );
          }
        }
      }
    } else {
      logger.warn?.(
        `[refineSections] Section "${section.title}": No fragments applied (${result.failed} failed)`
      );
      // DEBUG: Log detailed failure info for each failed fragment
      for (const res of result.results) {
        if (!res.applied) {
          const fragment = fragments.find(f => f.id === (res.match as any)?.fragmentId);
          logger.error?.(
            `[refineSections] Fragment failure details`,
            {
              fragmentId: fragment?.id,
              reason: res.reason,
              targetScore: res.match?.targetScore,
              contextBeforeScore: res.match?.contextBeforeScore,
              contextAfterScore: res.match?.contextAfterScore,
              combinedScore: res.match?.combinedScore,
              expectedTarget: fragment?.metadata?.target?.substring(0, 80),
            }
          );
        }
      }
    }
  }

  logger.log?.(
    `[refineSections] TextFragment mode complete: ${modifiedSectionIds.size} sections modified`
  );

  return {
    ...state,
    sections: updated,
    attempts: state.attempts + 1,
    recentlyModifiedIds: Array.from(modifiedSectionIds), // Track for smart validation
    textFragments: [], // Clear applied fragments
  };
}
