# User Documentation Workflow
name: user-docs
description: "Create end-user documentation including guides, tutorials, API references, and troubleshooting. Produces audience-appropriate documentation for product delivery."
author: "BMad"

# Critical variables from config
config_source: "{project-root}/bmad/bmm/config.yaml"
project_name: "{config_source}:project_name"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
user_skill_level: "{config_source}:user_skill_level"
date: system-generated

# Workflow components
installed_path: "{project-root}/bmad/bmm/workflows/5-delivery/user-docs"
instructions: "{installed_path}/instructions.md"

# Templates
getting_started_template: "{installed_path}/templates/getting-started-template.md"
user_guide_template: "{installed_path}/templates/user-guide-template.md"
api_reference_template: "{installed_path}/templates/api-reference-template.md"
faq_template: "{installed_path}/templates/faq-template.md"
troubleshooting_template: "{installed_path}/templates/troubleshooting-template.md"
release_notes_template: "{installed_path}/templates/release-notes-template.md"

# Output configuration
docs_output_folder: "{output_folder}/user-docs"
getting_started_output: "{docs_output_folder}/getting-started.md"
user_guide_output: "{docs_output_folder}/user-guide.md"
api_reference_output: "{docs_output_folder}/api-reference.md"
faq_output: "{docs_output_folder}/faq.md"
troubleshooting_output: "{docs_output_folder}/troubleshooting.md"
release_notes_output: "{docs_output_folder}/release-notes.md"

# Recommended input documents
recommended_inputs:
  - prd: "{output_folder}/PRD.md"
  - architecture: "{output_folder}/architecture.md"
  - epics: "{output_folder}/epics.md"

# Documentation types available
doc_types:
  - getting-started: "Quick start guide for new users"
  - user-guide: "Comprehensive usage documentation"
  - api-reference: "Technical API documentation"
  - faq: "Frequently asked questions"
  - troubleshooting: "Problem resolution guide"
  - release-notes: "Version changelog and updates"

# Audience levels
audience_levels:
  - beginner: "No prior experience assumed"
  - intermediate: "Basic familiarity expected"
  - advanced: "Technical users and developers"
  - mixed: "Tiered content for all levels"

standalone: true
