import type { RssSubscription } from '../../types/rss-subscription.types';

/**
 * Input for SubscribeToFeedUseCase (Port IN)
 *
 * Minimal data required to create a new RSS feed subscription.
 * Additional fields (id, tenantId, timestamps) are generated by the use case.
 */
export interface SubscribeToFeedInput {
  projectId: string;
  feedUrl: string;
  feedTitle: string;
  feedDescription?: string;
  category?: string;
  relevanceScore?: number;
  discoverySource?: 'tavily' | 'dataforseo' | 'manual';
  websiteUrl?: string;
  updateFrequency: 'hourly' | 'daily' | 'weekly';  // Required for subscriptions
}

/**
 * Port IN for RSS feed subscription creation
 *
 * Defines the public contract of the SubscribeToFeedUseCase.
 * Implemented by SubscribeToFeedUseCase in @casys/application.
 */
export interface SubscribeToFeedPort {
  /**
   * Subscribe to an RSS feed
   *
   * Validates input, checks for duplicates, and creates subscription.
   * Throws error if feed is already subscribed.
   *
   * @param tenantId - Tenant identifier for multi-tenancy
   * @param input - Subscription creation data
   * @returns Created RSS subscription with generated id and timestamps
   * @throws Error if feed is already subscribed or validation fails
   */
  execute(tenantId: string, input: SubscribeToFeedInput): Promise<RssSubscription>;
}
