/**
 * API Types
 *
 * Shared types for API route handlers.
 * Extracted from individual handlers to reduce duplication and improve clarity.
 *
 * @module api/types
 */

import type { UserAction } from "../telemetry/algorithm-tracer.ts";

// ============================================================================
// Algorithm API Types (from algorithm.ts)
// ============================================================================

export interface FeedbackRequest {
  traceId: string;
  userAction: UserAction;
  executionSuccess?: boolean;
  durationMs?: number;
}

export interface FeedbackResult {
  success: boolean;
  message: string;
  traceId: string;
}

export interface AlphaStatsResult {
  success: boolean;
  windowHours: number;
  stats: unknown; // AlgorithmTracer["getAlphaStats"] return type
}

export interface TracesResult {
  success: boolean;
  traces: unknown[];
  count: number;
}

export interface MetricsResult {
  success: boolean;
  windowHours: number;
  mode: string;
  metrics: unknown; // AlgorithmTracer["getMetrics"] return type
}

// ============================================================================
// Graph Insights Types (from graph-insights.ts)
// ============================================================================

/** Algorithm contribution to a node's discovery */
export interface AlgorithmScore {
  score: number;
  rank?: number;
  metadata?: Record<string, unknown>;
}

/** Unified insight item - a node discovered by one or more algorithms */
export interface InsightItem {
  id: string;
  name: string;
  type: "tool" | "capability";
  server?: string;
  algorithms: Record<string, AlgorithmScore>;
  combinedScore: number;
}

/** Response for /api/graph/insights */
export interface InsightsResponse {
  nodeId: string;
  nodeType: "tool" | "capability";
  items: InsightItem[];
  algorithmStats: Record<string, { count: number; avgScore: number }>;
}

// ============================================================================
// Traces API Types (from traces.ts)
// ============================================================================

/**
 * Trace received from packages/pml client (LocalExecutionTrace format).
 * Field names match packages/pml/src/tracing/types.ts for JSON compatibility.
 */
export interface IncomingTrace {
  /** Unique trace ID (UUID) - generated by package for parent-child linking (ADR-041) */
  traceId: string;
  /** Parent trace ID for nested capability calls (ADR-041) */
  parentTraceId?: string;
  /** Workflow ID for pending capability finalization (client-routed execution) */
  workflowId?: string;
  capabilityId: string;
  success: boolean;
  error?: string;
  durationMs: number;
  taskResults: IncomingTaskResult[];
  decisions: IncomingDecision[];
  timestamp: string;
  userId?: string;
}

export interface IncomingTaskResult {
  taskId: string;
  tool: string;
  args: Record<string, unknown>;
  result: unknown;
  success: boolean;
  durationMs: number;
  timestamp: string;
  layerIndex?: number; // Story 11.4: Parallel execution layer
}

export interface IncomingDecision {
  nodeId: string;
  outcome: string;
  condition?: string;
}

/** Request body for POST /api/traces */
export interface TracesRequest {
  traces: IncomingTrace[];
}

/** Response from POST /api/traces */
export interface TracesResponse {
  received: number;
  stored: number;
  errors?: string[];
}

// ============================================================================
// Tools API Types (from tools.ts)
// ============================================================================

/** UI metadata from MCP Apps (SEP-1865) */
export interface ToolUiMeta {
  resourceUri?: string;
  visibility?: Array<"model" | "app">;
  emits?: string[];
  accepts?: string[];
}

/** Input for a discovered tool from client */
export interface DiscoveredToolInput {
  name: string;
  description?: string;
  inputSchema?: Record<string, unknown>;
  /** MCP Apps UI metadata (Story 16.6) */
  uiMeta?: ToolUiMeta;
}

/** Fetched UI HTML content (Story 16.6) */
export interface FetchedUiHtmlInput {
  /** Resource URI (e.g., "ui://mcp-std/table-viewer") */
  resourceUri: string;
  /** HTML content */
  content: string;
  /** MIME type */
  mimeType?: string;
}

/** Discovery result for a single MCP server */
export interface DiscoveryResultInput {
  serverName: string;
  tools: DiscoveredToolInput[];
  error?: string;
  /** Fetched UI HTML content (Story 16.6) */
  uiHtml?: FetchedUiHtmlInput[];
}

/**
 * MCP server spawn config from client .pml.json
 * Tech-spec 01.5: Server Config Sync
 */
export interface ObservedConfig {
  /** Command to spawn the server (deno, npx, uvx, etc.) */
  command: string;
  /** Arguments for the command */
  args: string[];
  /** Environment variables (placeholders only, e.g., "${API_KEY}") */
  env?: Record<string, string>;
}

/** Request body for POST /api/tools/sync */
export interface ToolsSyncRequest {
  tools: DiscoveryResultInput[];
  /** Tech-spec 01.5: Server spawn configs from .pml.json */
  observedConfig?: Record<string, ObservedConfig>;
}

// ============================================================================
// Routing API Types (from routing.ts)
// ============================================================================

/** Package-expected routing config format */
export interface RoutingResponse {
  version: string;
  clientTools: string[];
  serverTools: string[];
  defaultRouting: "client" | "server";
}

// ============================================================================
// Emergence API Types (from emergence.ts) - internal only
// ============================================================================

/** History snapshot for phase transition detection (in-memory) */
export interface EmergenceSnapshot {
  timestamp: number;
  entropy: number;
  stability: number;
  diversity: number;
  velocity: number;
  accuracy: number;
}

// ============================================================================
// Validation Constants
// ============================================================================

/** UUID regex for validation (accepts v4 and v7) */
export const UUID_REGEX = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/** Valid user actions for algorithm feedback */
export const VALID_USER_ACTIONS: UserAction[] = [
  "selected",
  "ignored",
  "explicit_rejection",
];

/** Valid algorithm modes */
export const VALID_MODES = ["active_search", "passive_suggestion"] as const;
export type AlgorithmMode = (typeof VALID_MODES)[number];

/** Max length for tool/server names */
export const MAX_NAME_LENGTH = 256;

/** Valid name pattern for tools/servers */
export const VALID_NAME_PATTERN = /^[a-zA-Z0-9_\-\.]+$/;

// ============================================================================
// Algorithm Weights
// ============================================================================

/** Algorithm weights for combined score calculation */
export const ALGO_WEIGHTS: Record<string, number> = {
  neighbors: 1.0,
  co_occurrence: 0.9,
  louvain: 0.8,
  adamic_adar: 0.7,
  hyperedge: 0.6,
  spectral: 0.5,
};
