/**
 * Tracing Types for packages/pml
 *
 * Story 14.5b: Types for execution trace collection in sandboxed capabilities.
 *
 * **CRITICAL:** These types are ALIGNED with server types but NOT imported.
 * The `packages/pml` package is standalone (jsr:@casys/pml) and cannot
 * import from `src/*`.
 *
 * Field names match server's ExecutionTrace schema (migration 020) for
 * JSON serialization compatibility when syncing to cloud.
 *
 * @module tracing/types
 */

/**
 * JSON-serializable value (mirrors src/capabilities/types/schema.ts)
 */
export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

/**
 * Task result recorded during sandbox execution.
 *
 * Field names aligned with server's TraceTaskResult:
 * - taskId: string
 * - tool: string ("namespace:action")
 * - args: Record<string, JsonValue>
 * - result: JsonValue
 * - success: boolean
 * - durationMs: number
 */
export interface TraceTaskResult {
  /** Unique ID for this task (auto-generated) */
  taskId: string;

  /** Tool identifier in "namespace:action" format */
  tool: string;

  /** Arguments passed to the tool (will be sanitized) */
  args: Record<string, JsonValue>;

  /** Result returned by the tool (will be sanitized) */
  result: JsonValue;

  /** Whether the tool call succeeded */
  success: boolean;

  /** Call duration in milliseconds */
  durationMs: number;

  /** Timestamp when call was made (ISO string for serialization) */
  timestamp: string;

  /**
   * Story 11.4: DAG layer index for TraceTimeline visualization
   * - Layer 0: root tasks (no dependencies)
   * - Layer N: tasks that depend on layer N-1
   * Computed by server, passed in execute_locally response
   */
  layerIndex?: number;
}

/**
 * Branch decision during execution (for capabilities with control flow).
 *
 * Aligned with server's BranchDecision type.
 */
export interface BranchDecision {
  /** ID of the decision node */
  nodeId: string;

  /** Outcome taken (e.g., "true", "false") */
  outcome: string;

  /** Condition expression (optional, for debugging) */
  condition?: string;
}

/**
 * Local execution trace generated by sandbox.
 *
 * This type serializes to JSON compatible with server's ExecutionTrace.
 * Server will generate id, executedAt, and compute priority via TD-Error.
 *
 * Field alignment with server (migration 020):
 * - capabilityId → capability_id
 * - success → success
 * - durationMs → duration_ms
 * - taskResults → task_results (JSONB)
 * - decisions → decisions (JSONB)
 */
export interface LocalExecutionTrace {
  /** Unique trace ID (UUID) - generated by package for parent-child linking */
  traceId: string;

  /** Parent trace ID for nested capability calls (UUID) */
  parentTraceId?: string;

  /** Workflow ID for pending capability finalization (client-routed execution) */
  workflowId?: string;

  /**
   * FQDN of the executed capability (e.g., "casys.tools.fake:person")
   * Optional when workflowId is present (capability created server-side)
   */
  capabilityId?: string;

  /** Whether execution completed successfully */
  success: boolean;

  /** Error message if failed */
  error?: string;

  /** Total execution duration in milliseconds */
  durationMs: number;

  /** Results from each mcp.* call */
  taskResults: TraceTaskResult[];

  /** Branch decisions made during execution (if any) */
  decisions: BranchDecision[];

  /** ISO timestamp when trace was created */
  timestamp: string;

  /** User ID (for multi-tenancy) */
  userId?: string;
}

/**
 * Configuration for trace syncing to cloud.
 */
export interface TraceSyncConfig {
  /** Cloud URL for sync (null = standalone mode, no sync) */
  cloudUrl: string | null;

  /** Max traces per batch (default: 10) */
  batchSize: number;

  /** Max retries for failed sync (default: 3) */
  maxRetries: number;

  /** API key for cloud authentication (optional) */
  apiKey?: string;
}

/**
 * Default sync configuration.
 */
export const DEFAULT_SYNC_CONFIG: TraceSyncConfig = {
  cloudUrl: null, // Standalone by default
  batchSize: 10,
  maxRetries: 3,
};

/**
 * Response from cloud trace sync endpoint.
 */
export interface TraceSyncResponse {
  /** Number of traces received */
  received: number;

  /** Number of traces stored successfully */
  stored: number;

  /** Any errors encountered */
  errors?: string[];
}
