/**
 * Tracing Types for packages/pml
 *
 * Now imports base types from @casys/pml-types and extends locally.
 *
 * @module tracing/types
 */

// Re-export shared types
export type {
  BaseExecutionTrace,
  BranchDecision,
  JsonValue,
  TraceTaskResult,
} from "@casys/pml-types";

import type { BaseExecutionTrace } from "@casys/pml-types";

/**
 * Local execution trace generated by sandbox.
 *
 * Extends BaseExecutionTrace (shared contract) with PML-specific fields.
 * Server will generate DB id, compute priority via TD-Error, etc.
 */
export interface LocalExecutionTrace extends BaseExecutionTrace {
  /** Workflow ID for pending capability finalization (client-routed execution) */
  workflowId?: string;
}

/**
 * Configuration for trace syncing to cloud.
 */
export interface TraceSyncConfig {
  /** Cloud URL for sync (null = standalone mode, no sync) */
  cloudUrl: string | null;

  /** Max traces per batch (default: 10) */
  batchSize: number;

  /** Max retries for failed sync (default: 3) */
  maxRetries: number;

  /** API key for cloud authentication (optional) */
  apiKey?: string;
}

/**
 * Default sync configuration.
 */
export const DEFAULT_SYNC_CONFIG: TraceSyncConfig = {
  cloudUrl: null, // Standalone by default
  batchSize: 10,
  maxRetries: 3,
};

/**
 * Response from cloud trace sync endpoint.
 */
export interface TraceSyncResponse {
  /** Number of traces received */
  received: number;

  /** Number of traces stored successfully */
  stored: number;

  /** Any errors encountered */
  errors?: string[];
}
